# Generated by Django 3.2.9 on 2021-11-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20211117_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='raitingID',
            new_name='ratingID',
        ),
    ]
